language: java

matrix:
  include:
    - env:
      - eclipselink.version='2.7.3'
      - hsqldb.version='2.4.0'
    - env:
      - eclipselink.version='2.7.2'
      - hsqldb.version='2.4.0'
    - env:
      - eclipselink.version='2.7.3'
      - hsqldb.version='2.2.8'
    - env:
      - eclipselink.version='2.7.2'
      - hsqldb.version='2.2.8'

addons:
  apt:
    packages:
    - oracle-java8-installer

cache:
  directories:
    - $HOME/.m2

sudo: false

install: true

script:
  - "mvn -version"
  - "mvn clean test dependency:list -U -Declipselink.version=${eclipselink.version} -Dhsqldb.version=${hsqldb.version}"