--
-- Sample dataset containing a number of Hotels in various Cities across the world.  The reviews are entirely fictional :)
--

create TABLE simplentity (
	id bigint generated by default as identity,
	country varchar(256),
	name varchar(256),
	state varchar(256),
	map varchar(256)
);
